DEFINE 
//Total de Entregas
	MEASURE F_logistica[Total de Entregas] =
		COUNT ( F_logistica[ID_Pedido] )


//Total de Entregas no Prazo		
	MEASURE F_logistica[Total de Entregas no Prazo] =
		CALCULATE ( 
			[Total de Entregas],
			F_logistica[Status_Entrega] = "No Prazo"
		)
		

EVALUATE
	SUMMARIZECOLUMNS (
		"Total de Entregas", [Total de Entregas],
		"Total de Entregas no Prazo", [Total de Entregas no Prazo]
	)


//CRIAÇÃO DA TABELA CALENDÁRIO
EVALUATE
ADDCOLUMNS (
	CALENDARAUTO (),
	"Dia", DAY ( [Date] ),
	"Mês", MONTH ( [Date] ),
	"Ano", YEAR ( [Date] ),
	"Dia da Semana", WEEKDAY ( [Date], 1 ),
	"Dia da Semana por Extenso", FORMAT ( [Date], "dddd" ),
	"Mês Curto", FORMAT ( [Date], "mmm" ),
	"Mês por Extenso", FORMAT ( [Date], "mmmm" ),
	"Mês/Ano", FORMAT ( [Date], "mmm/yyyy" ),
	"Mês/Ano Ordenado", FORMAT ( [Date], "yyyymm" ),
	"Trimestre", FORMAT ( [Date], "Q" ) & "º Trim.",
	"Semestre", IF ( MONTH ( [Date] ) <= 6, "1º Semestre", "2º Semestre" )
)