EVALUATE
F_logistica

DEFINE 
//Total de Entregas
	MEASURE F_logistica[Total de Entregas] =
		COUNT ( F_logistica[ID_Pedido] )

//Total de Entregas no Prazo		
	MEASURE F_logistica[Total de Entregas no Prazo] =
		CALCULATE ( 
			[Total de Entregas],
			F_logistica[Status_Entrega] = "No Prazo"
		)
		
//Total de Entregas no Antecipado		
	MEASURE F_logistica[Total de Entregas no Antecipado] =
		CALCULATE ( 
			[Total de Entregas],
			F_logistica[Status_Entrega] = "Antecipado"
		)
		
//Total de Entregas no Atrasado		
	MEASURE F_logistica[Total de Entregas no Atrasado] =
		CALCULATE ( 
			[Total de Entregas],
			F_logistica[Status_Entrega] = "Atrasado"
		)
		
		
		
// Percentual de Entregas por Equipe
	MEASURE F_logistica[Percentual de Entregas por Equipe] =
		VAR TotalPorEquipe = 
		    CALCULATE(
		        COUNT(F_logistica[ID_Pedido]), 
		        ALLEXCEPT(F_logistica, F_logistica[Equipe_Entrega])
		    )
		    
		RETURN
		    DIVIDE(TotalPorEquipe, [Total de Entregas], 0) * 100
		

EVALUATE
	SUMMARIZECOLUMNS (
		"Total de Entregas", [Total de Entregas],
		"Total de Entregas no Prazo", [Total de Entregas no Prazo],
		"Total de Entregas no Antecipado", [Total de Entregas no Antecipado],
		"Total de Entregas no Atrasado", [Total de Entregas no Atrasado],
		"Percentual de Entregas por Equipe", [Percentual de Entregas por Equipe]
	)


//CRIAÇÃO DA TABELA CALENDÁRIO
EVALUATE
ADDCOLUMNS (
	CALENDARAUTO (),
	"Dia", DAY ( [Date] ),
	"Mês", MONTH ( [Date] ),
	"Ano", YEAR ( [Date] ),
	"Dia da Semana", WEEKDAY ( [Date], 1 ),
	"Dia da Semana por Extenso", FORMAT ( [Date], "dddd" ),
	"Mês Curto", FORMAT ( [Date], "mmm" ),
	"Mês por Extenso", FORMAT ( [Date], "mmmm" ),
	"Mês/Ano", FORMAT ( [Date], "mmm/yyyy" ),
	"Mês/Ano Ordenado", FORMAT ( [Date], "yyyymm" ),
	"Trimestre", FORMAT ( [Date], "Q" ) & "º Trim.",
	"Semestre", IF ( MONTH ( [Date] ) <= 6, "1º Semestre", "2º Semestre" )
)